'use strict';

// ********************* BTS OF JS *******************
/* AN OVERVIEW
   JS IS A :
   HIGH-LVEL: WE DON NOT HAVE TO MANAGE RESOURCES AT ALL LIKE WE NEED TO DO IN C,BUT PROGRAMS WILL NEVER BE AS FAST AS THEM 
   PROTOTYPE-BASE-OBJECT-ORIENTED: EVERYTHING IN JS IS OBJECT EXCEPT FOR PRIMITIVE VALUES
   MULTI-PARADIGM : "PARADIGM": AN APPROACH AND MINDSET OF STRUCTURING CODE WHICH WILL DIRECT YOUR CODING STYLE AND TECHNIQUE 
   THREE PROPULAR PARADIGM ARE : 
   1. PROCEDURAL 
   2. OOPS
   3. FUNCTIONAL
   JS CAN DO ALL OF IT 
   INTERPRETED OR JUST IN TIME COMPILED
   DYNAMIC: WE DO NOT NEED TO ASSIGN DATA TYPES TO VARIABLES
   SINGLE-THREADED: RUNS ONE TASK AT A TIME
   GARBAGE-COLLECTED: POWERFULL ALGO IN JS  THAT AUTOMATICALLY REMOVE OLD UNSED OBJECT FROM THE MEMORY (HELPER GUY THAT MANAGES MEMORY BY CLEANING IT FROM TIME TO TIME)
   FIRST-CLASS-FUNCTION: FUNCTIONS ARE TREATED AS VARIABLES WE CAN CALL FUNCTIONS IN OTHER FUNCTIONS,PASS FUNCTIONS IN FUNCTIONS AND RETURN FUNCTIONS
   NON BLOCKING EVENT LOOP CONCURRENCY MODEL: "CM" MEANS HOW JS HANDLES MULTIPLE TASKS HAPPENING AT THE SAME TIME, JS IS SINGLE THREADED SO IT DOES ONE TASK AT A TIME
 */
